name: utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  global_configuration: ^2.0.0
  shared_preferences: ^2.3.2
  flutter_localization: ^0.3.0
  http: ^1.2.2
  intl: ^0.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
   - lib/assets/images/